### ISSUE TITLE
Support major release rubocop version >= 1.0.0

### ISSUE THREAD

**Issue by TSMMark** [rubocop-hq/rubocop-sequel#12]
```
Bundler could not find compatible versions for gem "rubocop":
  In Gemfile:
    rubocop (~> 1.2.0)

    rubocop-sequel was resolved to 0.0.6, which depends on
      rubocop (>= 0.55, ~> 0.55)
```

Is there any work that needs to be done to support the >= 1.0.0 releases? 

There are some breaking changes listed in [rubocop changelog](https://github.com/rubocop-hq/rubocop/blob/master/CHANGELOG.md). Does this gem need any code changes or just update to the gemspec?

https://github.com/rubocop-hq/rubocop-sequel/blob/7099c0bd3ea5c04a2e3dadb7c0f63fa18f2c3436/rubocop-sequel.gemspec#L18

Thanks!

**Comment by tejasbubane** [comment]
I think this can be closed now?
