### ISSUE TITLE
Invitation to join RuboCop HQ

### ISSUE THREAD

**Issue by bbatsov** [rubocop-hq/rubocop-sequel#5]
Hey there!

I've recently created https://github.com/rubocop-hq to serve as the new home of RuboCop and related projects (see https://speakerdeck.com/bbatsov/all-about-rubocop-rubykaigi-2018?slide=157 for some background on this). I'd love to see rubocop-sequel live under the same organization as RuboCop itself.

Let me know if you're interested in doing this and we'll hash out the details later.

**Comment by cyberdelia** [comment]
Sure, tell me more.

**Comment by bbatsov** [comment]
I'll send you an invitation to join the org now. After you accept it you'll be able to transfer the repo there . Afterwards it's mostly business as usual, but I hope the higher visibility of the project will gather more contributors and users for it.
